#!/bin/bash

set -e

script_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

${script_dir}/isp-support/install-dependencies-ubuntu1804
PATH=$HOME/.local/bin:$PATH:/opt/isp/bin
ISP_PREFIX=/opt/isp/
cd ${script_dir}
make -j `nproc`
make kernel
make test
