FROM ubuntu:xenial-20171114

RUN apt-get update && \
    apt-get install -yq \
            less \
            emacs \
            vim \
            nano \
            apt-utils && \
    rm -rf /var/lib/apt/lists/*


ARG SDK_VERSION
ARG SDK_PACKAGE=isp-sdk_${SDK_VERSION}_amd64.deb

COPY ${SDK_PACKAGE} .

RUN apt-get update && \
    apt-get install -yq ./${SDK_PACKAGE} && \
    rm ./${SDK_PACKAGE}  && \
    rm -rf /var/lib/apt/lists/*
