.PHONY: all
.PHONY: toolchain
.PHONY: sdk
.PHONY: docker-sdk
.PHONY: run-docker-sdk
.PHONY: policy-tool
.PHONY: fesvr
.PHONY: tinycrypt
.PHONY: dover-spike
.PHONY: free-rtos
.PHONY: opcodes
.PHONY: emptyfs
.PHONY: sdk-test
.PHONY: sdk-check
.PHONY: documentation
.PHONY: clean
.PHONY: cleanall

SHELL:=/bin/bash

SDK_VERSION:=0.0.0

# Ensure appropriate ENV variables are set
ifndef DOVER
  $(error variable DOVER not defined)
endif

NPROCS:=1
OS:=$(shell uname -s)

ifeq ($(OS),Linux)
  NPROCS:=$(shell grep -c ^processor /proc/cpuinfo)
endif

MAKEFLAGS += -j$(NPROCS)

all:
	$(MAKE) toolchain
	$(MAKE) policy-tool tinycrypt dover-spike
	$(MAKE) dover-os
	$(MAKE) emptyfs
	$(MAKE) free-rtos

toolchain:
	$(MAKE) -C ../riscv-gnu-toolchain

sdk: all documentation
	./build-sdk -o $(DOVER) -s $(SDK_VERSION)

# DOCKER_BUILD_ARGS is to allow passing additional parameters to build such as
# proxy settings without polluting the Makefile for those who do not need it.
# For most this does not need to be set

docker-sdk: sdk
	docker build $(DOCKER_BUILD_ARGS) -t isp-sdk:latest \
		--build-arg SDK_VERSION=$(SDK_VERSION) -f Dockerfile.sdk .

run-docker-sdk: docker-sdk
	./run-docker-sdk

policy-tool:
	$(MAKE) -C ../dover-policies

fesvr: $(DOVER)/include/fesvr

$(DOVER)/include/fesvr:
	$(MAKE) -C ../riscv-fesvr

tinycrypt:
	$(MAKE) -C ../tinycrypt

dover-spike: $(DOVER)/include/fesvr
	$(MAKE) -C ../riscv-isa-sim

free-rtos:
	$(MAKE) -C ../FreeRTOS-RISCV

dover-os:
	$(MAKE) -C ../dover-os

# Do not 'make opcodes' unless you have actually modified
# source files under riscv-opcodes.
# 'make opcodes' causes .h files to be sprinkled amongst various
# other repos, and then those repos have to be committed and pushed.
# When you check out, e.g. riscv-isa-sim, it comes with the .h files
# generated by 'make opcodes'.
opcodes:
	touch ../riscv-opcodes/opcodes-custom
	$(MAKE) -C ../riscv-opcodes install | tee -a ../riscv-opcodes/build.log

emptyfs:
	../dover-os/build/utils/fs_create $(DOVER)/empty.fs

sdk-test sdk-check:
	find sdk-tests -name "*~" -delete
	docker run --rm -i -v $(PWD)/sdk-tests:/sdk-tests -t isp-sdk:latest bats --tap sdk-tests/

documentation:
	$(MAKE) -C documentation

clean:
	$(MAKE) -C ../dover-policies clean
	$(MAKE) -C ../riscv-fesvr clean
	$(MAKE) -C ../tinycrypt clean
	$(MAKE) -C ../riscv-isa-sim clean
	$(MAKE) -C ../FreeRTOS-RISCV clean

cleanall: clean
	$(MAKE) -C ../riscv-gnu-toolchain clean
	$(MAKE) -C documentation clean
	rm -rf $(DOVER)
