#!/bin/bash

script_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
repo_file="$script_dir/repos.txt"
repo_root_dir="$script_dir/../"

while read repo; do
    if [[ $repo == \#* ]]; then
        echo "Skipping line" $repo
    else
        pushd "$repo_root_dir/$repo"  > /dev/null
        echo In $repo
        git "$@"
        echo ""
        popd > /dev/null
    fi
done < $repo_file
