#!/bin/bash

sudo apt-get install -y autoconf automake autogen autotools-dev curl \
    libmpc-dev libmpfr-dev libgmp-dev gawk build-essential \
    bison flex texinfo gperf iverilog libelf-dev socat \
    expat libexpat1-dev git python3 python3-setuptools \
    cmake ninja-build clang haskell-platform haskell-stack binutils-dev \
    python3-distutils python3-pytest \
    python3-pytest-xdist python3-pytest-timeout python3-pyelftools \
    git automake autoconf libtool g++ \
    cmake libboost-dev libboost-program-options-dev \
    libyaml-cpp-dev libgflags-dev \
    python3-psutil xterm verilator virtualenv python3-pip \
    libftdi1-2 libusb-1.0-0-dev libtinfo5

sudo stack upgrade --binary-only --allow-different-user --local-bin-path /usr/bin
