#!/bin/bash

if [[ -v http_proxy ]]; then
sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --keyserver-options http-proxy=$http_proxy --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
else
sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
fi
echo "deb https://download.mono-project.com/repo/ubuntu stable-bionic main" | sudo tee /etc/apt/sources.list.d/mono-official-stable.list
sudo apt update
sudo apt-get install -y autoconf automake autogen autotools-dev curl \
    libmpc-dev libmpfr-dev libgmp-dev gawk build-essential \
    bison flex texinfo gperf iverilog libelf-dev socat \
    expat libexpat1-dev git python3 python3-setuptools \
    cmake ninja-build clang haskell-platform haskell-stack binutils-dev \
    python3-distutils python3-pytest \
    python3-pytest-xdist python3-pytest-timeout python3-pyelftools \
    git mono-complete automake autoconf libtool g++ \
    libgtk2.0-dev screen uml-utilities gtk-sharp2 \
    cmake libboost-dev libboost-program-options-dev \
    libyaml-cpp-dev libgflags-dev \
    python3-psutil xterm verilator virtualenv python3-pip
stack upgrade --binary-only
echo 'export PATH=$HOME/.local/bin:$PATH:/opt/isp/bin' >> ~/.bashrc
echo 'export ISP_PREFIX=/opt/isp/' >> ~/.bashrc
