FROM ubuntu:xenial-20171114

RUN apt-get update && \
    apt-get install -yq \
            apt-utils \
            bats \
            emacs \
            less \
            nano \
            vim && \
    rm -rf /var/lib/apt/lists/*


ARG SDK_VERSION
ARG SDK_DISTRO
ARG SDK_PACKAGE=isp-sdk_${SDK_VERSION}_amd64.deb

COPY packages/${SDK_DISTRO}/${SDK_PACKAGE} .

RUN apt-get update && \
    apt-get install -yq ./${SDK_PACKAGE} && \
    rm ./${SDK_PACKAGE}  && \
    rm -rf /var/lib/apt/lists/*
